### ISSUE TITLE
Make a NPM / WebPack build

### ISSUE THREAD

**Issue by charlesfleche** [CarloCattano/PopularSynth#4]
This will allow to easily split synths in different js modules, have a single html template and let npm / webpack manages the build for us.

**Comment by CarloCattano** [comment]
interesting, do you have some documentation I can check about this matter?

**Comment by charlesfleche** [comment]
I'm doing it as we speak. I'll show you in more details during the next meetup if you are interested.

**Comment by CarloCattano** [comment]
sure, I really used npm in a blind way, but willing to learn the propper methods. to have the audio sketches on separate files its surely more convenient, so less hassle to add more later on

**Comment by charlesfleche** [comment]
I'm on it
