### ISSUE TITLE
Missing StartAudioContext

### ISSUE THREAD

**Issue by charlesfleche** [CarloCattano/PopularSynth#7]
`ReferenceError: StartAudioContext is not defined`

![image](https://user-images.githubusercontent.com/2563098/41237491-e1116f6c-6d93-11e8-89e5-15a0cbc2248e.png)

**Comment by CarloCattano** [comment]
Exactly what I thought. In the older versions I was referencing the
startaudiocontext script in the head. I didn't have the time to look at it
but it's an easy one to solve

**Comment by charlesfleche** [comment]
I'm on it
